import { initializeApp } from "firebase/app";
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';
import { getFunctions } from 'firebase/functions'; 
import { firebaseConfig } from "./config";
import * as firebaseui from "firebaseui";
const app = initializeApp(firebaseConfig);
export const db = getFirestore(app); 
export const functions = getFunctions(app);
export const auth = getAuth(app);
export const ui = new firebaseui.auth.AuthUI(auth);